return {
  id: toString(products[0]._id),
  name: products[0].name,
  category: products[0].category,
  quantity: products[0].quantity,
  price: products[0].price,
  discount: products[0].discount,
  warranty: products[0].warranty,
  img: products[0].img,
  dimimage: products[0].dimimg,
  quality: products[0].quality,
  delivery: products[0].delivery,
  returns: products[0].returns,
  pricing: products[0].pricing,
};
